version: '3.8'

services:
    tagged-image-service:
        build: .
        image: chrisjolly25/tagged-image-service:latest
        environment:
            - MYSQL_HOST=db # This will be 'db' when in docker. Need to align these
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_DB=${MYSQL_DB}
            - SERVICE_USER_PASSWORD=${SERVICE_USER_PASSWORD}
            - MYSQL_SERVICE_USERNAME=${MYSQL_SERVICE_USERNAME}
            - JWT_SECRET=${JWT_SECRET}
            - CLIENT_USERNAME=${CLIENT_USERNAME}
            - CLIENT_PASSWORD=${CLIENT_PASSWORD}
        ports:
            - '3000:3000'
        volumes:
            - './public:/usr/app/public'
        depends_on:
            db:
                condition: service_healthy
        networks:
            - back
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - './db/schema.sql:/docker-entrypoint-initdb.d/1.sql'
        networks:
            - back
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 5s
            retries: 10

networks:
    back:
        driver: bridge
